DROP TABLE IF EXISTS todos;

CREATE TABLE todos(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  title VARCHAR(255) NOT NULL,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  position INT NOT NULL DEFAULT 0
);

CREATE OR REPLACE FUNCTION reorder_todos(todo_ids bigint[]) RETURNS VOID
AS
$$
BEGIN
  FOR i IN 1 .. array_upper(todo_ids, 1)
   loop
      UPDATE todos
      SET position = i - 1
      WHERE id = todo_ids[i];
   END loop;
END;
$$ LANGUAGE plpgsql;
